# Generated by Django 5.1.6 on 2025-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100, unique=True, verbose_name='会员卡名称')),
                ('card_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('duration', models.IntegerField(verbose_name='有效天数')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='会员卡简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员卡信息',
                'verbose_name_plural': '会员卡信息',
                'db_table': 'card',
            },
        ),
    ]
