# Generated by Django 5.1.6 on 2025-04-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='profile',
        ),
    ]
