# Generated by Django 5.1.6 on 2025-04-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_user_order_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='profile',
            new_name='user',
        ),
    ]
