# Generated by Django 5.1.6 on 2025-04-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_rename_profile_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='profile',
        ),
    ]
