# Generated by Django 5.1.6 on 2025-02-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('release_year', models.IntegerField(verbose_name='上映年份')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('scriptwriter', models.CharField(max_length=100, verbose_name='编剧')),
                ('actor', models.CharField(max_length=200, verbose_name='演员')),
                ('region', models.CharField(choices=[(1, '中国大陆'), (2, '中国香港'), (3, '中国台湾'), (4, '美国'), (5, '韩国'), (6, '日本'), (7, '其他')], max_length=100, verbose_name='地区')),
                ('types', models.CharField(max_length=50, verbose_name='类型')),
                ('language', models.CharField(max_length=100, verbose_name='语言')),
                ('release_data', models.DateField(verbose_name='上映日期')),
                ('duration', models.CharField(max_length=50, verbose_name='时长(集数)')),
                ('alternate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='又名')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='图片链接')),
                ('rate', models.FloatField(blank=True, verbose_name='评分')),
                ('review', models.TextField(blank=True, max_length=500, verbose_name='简介')),
                ('is_hot', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否热门')),
                ('is_top', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否置顶')),
                ('quality', models.SmallIntegerField(blank=True, choices=[(1, '720p'), (2, '1080p'), (3, '4k')], verbose_name='清晰度')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='字幕')),
                ('update_info', models.CharField(blank=True, max_length=200, verbose_name='更新信息')),
                ('update_progress', models.CharField(blank=True, max_length=200, verbose_name='更新情况')),
                ('download_info', models.CharField(blank=True, max_length=500, verbose_name='网盘信息')),
                ('is_show', models.BooleanField(choices=[(False, '否'), (True, '是')], default=True, verbose_name='是否展示')),
                ('is_free', models.BooleanField(choices=[(False, '否'), (True, '是')], default=True, verbose_name='是否免费')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category', verbose_name='分类名')),
            ],
            options={
                'verbose_name': '电影管理',
                'verbose_name_plural': '电影管理',
                'db_table': '电影',
            },
        ),
    ]
