# Generated by Django 5.1.6 on 2025-02-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_actor_movie_actors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category_id',
            new_name='category',
        ),
    ]
