# Generated by Django 5.1.6 on 2025-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_category_id_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='region',
            field=models.CharField(choices=[('1', '中国大陆'), ('2', '中国香港'), ('3', '中国台湾'), ('4', '美国'), ('5', '韩国'), ('6', '日本'), ('7', '其他')], max_length=100, verbose_name='地区'),
        ),
    ]
